local flora = {}

-- lists are taken from the mod https://mods.factorio.com/mod/Noxys_Trees

local tiles_list = {
    ["dirt-1"]                       = {1,16},
    ["dirt-2"]                       = {1,16},
    ["dirt-3"]                       = {1,16},
    ["dirt-4"]                       = {1,16},
    ["dirt-5"]                       = {1,16},
    ["dirt-6"]                       = {1,16},
    ["dirt-7"]                       = {1,16},
    ["dry-dirt"]                     = {1,16},
    ["grass-1"]                      = {1,16},
    ["grass-2"]                      = {1,16},
    ["grass-3"]                      = {1,16},
    ["grass-4"]                      = {1,16},
    ["red-desert-0"]                 = {1,16},
    ["red-desert-1"]                 = {1,16},
    ["red-desert-2"]                 = {1,16},
    ["red-desert-3"]                 = {1,16},
    ["sand-1"]                       = {1,16},
    ["sand-2"]                       = {1,16},
    ["sand-3"]                       = {1,16},
    ["sand-4"]                       = {1,16},
    ["grass-medium"]                 = {1,16},
    ["grass"]                        = {1,16},
    ["grass-dry"]                    = {1,16},
    ["dirt-dark"]                    = {1,16},
    ["dirt"]                         = {1,16},
    ["red-desert"]                   = {1,16},
    ["red-desert-dark"]              = {1,16},
    ["sand-dark"]                    = {1,16},
    ["sand"]                         = {1,16},
    ["landfill"]                     = nil, -- Not fertile
    -- Alien biomes {17,80}
    ["grass-red"]                    = {17,80},
    ["grass-orange"]                 = {17,80},
    ["grass-yellow"]                 = {17,80},
    ["grass-yellow-fade"]            = {17,80},
    ["grass-purple-fade"]            = {17,80},
    ["grass-purple"]                 = {17,80},
    ["dirt-red-dark"]                = {17,80},
    ["dirt-brown-dark"]              = {17,80},
    ["grass-blue-fade"]              = {17,80},
    ["grass-blue"]                   = {17,80},
    ["dirt-red"]                     = {17,80},
    ["dirt-brown"]                   = {17,80},
    ["dirt-tan-dark"]                = {17,80},
    ["dirt-dull-dark"]               = {17,80},
    ["dirt-grey-dark"]               = {17,80},
    ["dirt-tan"]                     = {17,80},
    ["dirt-dull"]                    = {17,80},
    ["dirt-grey"]                    = {17,80},
    ["sand-red-dark"]                = {17,80},
    ["sand-orange-dark"]             = {17,80},
    ["sand-gold-dark"]               = {17,80},
    ["sand-dull-dark"]               = {17,80},
    ["sand-grey-dark"]               = {17,80},
    ["sand-red"]                     = {17,80},
    ["sand-orange"]                  = {17,80},
    ["sand-gold"]                    = {17,80},
    ["sand-dull"]                    = nil,
    ["sand-grey"]                    = nil,
    ["snow"]                         = {17,80},
    ["volcanic-cool"]                = {17,80},
    -- Alien biomes {17,80}6
    ["mineral-purple-dirt-1"]        = {17,80},
    ["mineral-purple-dirt-2"]        = {17,80},
    ["mineral-purple-dirt-3"]        = {17,80},
    ["mineral-purple-dirt-4"]        = {17,80},
    ["mineral-purple-dirt-5"]        = {17,80},
    ["mineral-purple-dirt-6"]        = {17,80},
    ["mineral-purple-sand-1"]        = {17,80},
    ["mineral-purple-sand-2"]        = {17,80},
    ["mineral-purple-sand-3"]        = {17,80},
    ["mineral-violet-dirt-1"]        = {17,80},
    ["mineral-violet-dirt-2"]        = {17,80},
    ["mineral-violet-dirt-3"]        = {17,80},
    ["mineral-violet-dirt-4"]        = {17,80},
    ["mineral-violet-dirt-5"]        = {17,80},
    ["mineral-violet-dirt-6"]        = {17,80},
    ["mineral-violet-sand-1"]        = {17,80},
    ["mineral-violet-sand-2"]        = {17,80},
    ["mineral-violet-sand-3"]        = {17,80},
    ["mineral-red-dirt-1"]           = {17,80},
    ["mineral-red-dirt-2"]           = {17,80},
    ["mineral-red-dirt-3"]           = {17,80},
    ["mineral-red-dirt-4"]           = {17,80},
    ["mineral-red-dirt-5"]           = {17,80},
    ["mineral-red-dirt-6"]           = {17,80},
    ["mineral-red-sand-1"]           = {17,80},
    ["mineral-red-sand-2"]           = {17,80},
    ["mineral-red-sand-3"]           = {17,80},
    ["mineral-brown-dirt-1"]         = {17,80},
    ["mineral-brown-dirt-2"]         = {17,80},
    ["mineral-brown-dirt-3"]         = {17,80},
    ["mineral-brown-dirt-4"]         = {17,80},
    ["mineral-brown-dirt-5"]         = {17,80},
    ["mineral-brown-dirt-6"]         = {17,80},
    ["mineral-brown-sand-1"]         = {17,80},
    ["mineral-brown-sand-2"]         = {17,80},
    ["mineral-brown-sand-3"]         = {17,80},
    ["mineral-tan-dirt-1"]           = {17,80},
    ["mineral-tan-dirt-2"]           = {17,80},
    ["mineral-tan-dirt-3"]           = {17,80},
    ["mineral-tan-dirt-4"]           = {17,80},
    ["mineral-tan-dirt-5"]           = {17,80},
    ["mineral-tan-dirt-6"]           = {17,80},
    ["mineral-tan-sand-1"]           = {17,80},
    ["mineral-tan-sand-2"]           = {17,80},
    ["mineral-tan-sand-3"]           = {17,80},
    ["mineral-aubergine-dirt-1"]     = {17,80},
    ["mineral-aubergine-dirt-2"]     = {17,80},
    ["mineral-aubergine-dirt-3"]     = {17,80},
    ["mineral-aubergine-dirt-4"]     = {17,80},
    ["mineral-aubergine-dirt-5"]     = {17,80},
    ["mineral-aubergine-dirt-6"]     = {17,80},
    ["mineral-aubergine-sand-1"]     = {17,80},
    ["mineral-aubergine-sand-2"]     = {17,80},
    ["mineral-aubergine-sand-3"]     = {17,80},
    ["mineral-dustyrose-dirt-1"]     = {17,80},
    ["mineral-dustyrose-dirt-2"]     = {17,80},
    ["mineral-dustyrose-dirt-3"]     = {17,80},
    ["mineral-dustyrose-dirt-4"]     = {17,80},
    ["mineral-dustyrose-dirt-5"]     = {17,80},
    ["mineral-dustyrose-dirt-6"]     = {17,80},
    ["mineral-dustyrose-sand-1"]     = {17,80},
    ["mineral-dustyrose-sand-2"]     = {17,80},
    ["mineral-dustyrose-sand-3"]     = {17,80},
    ["mineral-beige-dirt-1"]         = {17,80},
    ["mineral-beige-dirt-2"]         = {17,80},
    ["mineral-beige-dirt-3"]         = {17,80},
    ["mineral-beige-dirt-4"]         = {17,80},
    ["mineral-beige-dirt-5"]         = {17,80},
    ["mineral-beige-dirt-6"]         = {17,80},
    ["mineral-beige-sand-1"]         = {17,80},
    ["mineral-beige-sand-2"]         = {17,80},
    ["mineral-beige-sand-3"]         = {17,80},
    ["mineral-cream-dirt-1"]         = {17,80},
    ["mineral-cream-dirt-2"]         = {17,80},
    ["mineral-cream-dirt-3"]         = {17,80},
    ["mineral-cream-dirt-4"]         = {17,80},
    ["mineral-cream-dirt-5"]         = {17,80},
    ["mineral-cream-dirt-6"]         = {17,80},
    ["mineral-cream-sand-1"]         = {17,80},
    ["mineral-cream-sand-2"]         = {17,80},
    ["mineral-cream-sand-3"]         = {17,80},
    ["mineral-black-dirt-1"]         = {17,80},
    ["mineral-black-dirt-2"]         = {17,80},
    ["mineral-black-dirt-3"]         = {17,80},
    ["mineral-black-dirt-4"]         = {17,80},
    ["mineral-black-dirt-5"]         = {17,80},
    ["mineral-black-dirt-6"]         = {17,80},
    ["mineral-black-sand-1"]         = {17,80},
    ["mineral-black-sand-2"]         = {17,80},
    ["mineral-black-sand-3"]         = {17,80},
    ["mineral-grey-dirt-1"]          = {17,80},
    ["mineral-grey-dirt-2"]          = {17,80},
    ["mineral-grey-dirt-3"]          = {17,80},
    ["mineral-grey-dirt-4"]          = {17,80},
    ["mineral-grey-dirt-5"]          = {17,80},
    ["mineral-grey-dirt-6"]          = {17,80},
    ["mineral-grey-sand-1"]          = {17,80},
    ["mineral-grey-sand-2"]          = {17,80},
    ["mineral-grey-sand-3"]          = {17,80},
    ["mineral-white-dirt-1"]         = {17,80},
    ["mineral-white-dirt-2"]         = {17,80},
    ["mineral-white-dirt-3"]         = {17,80},
    ["mineral-white-dirt-4"]         = {17,80},
    ["mineral-white-dirt-5"]         = {17,80},
    ["mineral-white-dirt-6"]         = {17,80},
    ["mineral-white-sand-1"]         = {17,80},
    ["mineral-white-sand-2"]         = {17,80},
    ["mineral-white-sand-3"]         = {17,80},
    ["vegetation-turquoise-grass-1"] = {17,80},
    ["vegetation-turquoise-grass-2"] = {17,80},
    ["vegetation-green-grass-1"]     = {17,80},
    ["vegetation-green-grass-2"]     = {17,80},
    ["vegetation-green-grass-3"]     = {17,80},
    ["vegetation-green-grass-4"]     = {17,80},
    ["vegetation-olive-grass-1"]     = {17,80},
    ["vegetation-olive-grass-2"]     = {17,80},
    ["vegetation-yellow-grass-1"]    = {17,80},
    ["vegetation-yellow-grass-2"]    = {17,80},
    ["vegetation-orange-grass-1"]    = {17,80},
    ["vegetation-orange-grass-2"]    = {17,80},
    ["vegetation-red-grass-1"]       = {17,80},
    ["vegetation-red-grass-2"]       = {17,80},
    ["vegetation-violet-grass-1"]    = {17,80},
    ["vegetation-violet-grass-2"]    = {17,80},
    ["vegetation-purple-grass-1"]    = {17,80},
    ["vegetation-purple-grass-2"]    = {17,80},
    ["vegetation-mauve-grass-1"]     = {17,80},
    ["vegetation-mauve-grass-2"]     = {17,80},
    ["vegetation-blue-grass-1"]      = {17,80},
    ["vegetation-blue-grass-2"]      = {17,80},
    ["volcanic-orange-heat-1"]       = nil,
    ["volcanic-orange-heat-2"]       = nil,
    ["volcanic-orange-heat-3"]       = nil,
    ["volcanic-orange-heat-4"]       = nil,
    ["volcanic-green-heat-1"]        = {17,80},
    ["volcanic-green-heat-2"]        = {17,80},
    ["volcanic-green-heat-3"]        = {17,80},
    ["volcanic-green-heat-4"]        = {17,80},
    ["volcanic-blue-heat-1"]         = nil,
    ["volcanic-blue-heat-2"]         = nil,
    ["volcanic-blue-heat-3"]         = nil,
    ["volcanic-blue-heat-4"]         = nil,
    ["volcanic-purple-heat-1"]       = nil,
    ["volcanic-purple-heat-2"]       = nil,
    ["volcanic-purple-heat-3"]       = nil,
    ["volcanic-purple-heat-4"]       = nil,
    ["frozen-snow-0"]                = {79,79},
    ["frozen-snow-1"]                = {79,79},
    ["frozen-snow-2"]                = {79,79},
    ["frozen-snow-3"]                = {79,79},
    ["frozen-snow-4"]                = {79,79},
    ["frozen-snow-5"]                = {79,79},
    ["frozen-snow-6"]                = {79,79},
    ["frozen-snow-7"]                = {79,79},
    ["frozen-snow-8"]                = {79,79},
    ["frozen-snow-9"]                = {79,79}
}

local trees_list = {
    "tree-01",
    "tree-01",
    "tree-02",
    "tree-02-red",
    "tree-03",
    "tree-04",
    "tree-05",
    "tree-06",
    "tree-06-brown",
    "tree-07",
    "tree-08",
    "tree-08-brown",
    "tree-08-red",
    "tree-09",
    "tree-09-brown",
    "tree-09-red",
    -- Alien Biomes
    "tree-wetland-a",
    "tree-wetland-b",
    "tree-wetland-c",
    "tree-wetland-d",
    "tree-wetland-e",
    "tree-wetland-f",
    "tree-wetland-g",
    "tree-wetland-h",
    "tree-wetland-i",
    "tree-wetland-j",
    "tree-wetland-k",
    "tree-wetland-l",
    "tree-wetland-m",
    "tree-wetland-n",
    "tree-wetland-o",
    "tree-grassland-a",
    "tree-grassland-b",
    "tree-grassland-c",
    "tree-grassland-d",
    "tree-grassland-e",
    "tree-grassland-f",
    "tree-grassland-g",
    "tree-grassland-h",
    "tree-grassland-h2",
    "tree-grassland-h3",
    "tree-grassland-i",
    "tree-grassland-k",
    "tree-grassland-l",
    "tree-grassland-m",
    "tree-grassland-n",
    "tree-grassland-0",
    "tree-grassland-p",
    "tree-grassland-q",
    "tree-dryland-a",
    "tree-dryland-b",
    "tree-dryland-c",
    "tree-dryland-d",
    "tree-dryland-e",
    "tree-dryland-f",
    "tree-dryland-g",
    "tree-dryland-h",
    "tree-dryland-i",
    "tree-dryland-j",
    "tree-dryland-k",
    "tree-dryland-l",
    "tree-dryland-m",
    "tree-dryland-n",
    "tree-dryland-o",
    "tree-desert-a",
    "tree-desert-b",
    "tree-desert-c",
    "tree-desert-d",
    "tree-desert-e",
    "tree-desert-f",
    "tree-desert-g",
    "tree-desert-h",
    "tree-desert-i",
    "tree-desert-j",
    "tree-desert-k",
    "tree-desert-l",
    "tree-desert-m",
    "tree-desert-n",
    "tree-snow-a",
    "tree-volcanic-a"
}

function flora.check_tile_for_tree(t_tile)
    if not t_tile or not t_tile.valid then return end
    local t_tree = tiles_list[t_tile.name]
    if t_tree then return trees_list[math.random(t_tree[1], t_tree[2])] end
end

return flora